// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VulnerabilitiesApp.Models;

namespace VulnerabilitiesApp.Migrations
{
    [DbContext(typeof(VulnerabilitiesAppContext))]
    [Migration("20181209205146_MyFirstMigration2")]
    partial class MyFirstMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VulnerabilitiesApp.Models.Anunt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activ");

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descriere");

                    b.Property<long>("IdCategorie");

                    b.Property<long>("IdSubCategorie");

                    b.Property<long>("IdValuta");

                    b.Property<long>("Pret");

                    b.Property<bool>("Sters");

                    b.Property<string>("Titlu");

                    b.HasKey("Id");

                    b.ToTable("Anunt");
                });

            modelBuilder.Entity("VulnerabilitiesApp.Models.AnuntUtilizator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("IdAnunt");

                    b.Property<long>("IdUtilizator");

                    b.Property<bool>("Sters");

                    b.HasKey("Id");

                    b.ToTable("AnuntUtilizator");
                });

            modelBuilder.Entity("VulnerabilitiesApp.Models.Categorie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume");

                    b.HasKey("Id");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("VulnerabilitiesApp.Models.Utilizator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Nume");

                    b.Property<string>("Prenume");

                    b.Property<bool>("Sters");

                    b.Property<string>("Telefon");

                    b.HasKey("Id");

                    b.ToTable("Utilizator");
                });

            modelBuilder.Entity("VulnerabilitiesApp.Models.Valuta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume");

                    b.HasKey("Id");

                    b.ToTable("Valuta");
                });
#pragma warning restore 612, 618
        }
    }
}
